# This rule is not used by the project mysql-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to db.cloudstudy.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysql-viewer-role
rules:
- apiGroups:
  - db.cloudstudy.com
  resources:
  - mysqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.cloudstudy.com
  resources:
  - mysqls/status
  verbs:
  - get
